name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start gRPC Server in Background
        run: |
          python -m app.nlp &
          echo "Waiting for gRPC server on port 50051..."
          for i in {1..40}; do
            nc -z localhost 50051 && echo "Server is up!" && break
            echo "Waiting... ($i/40)"
            sleep 3
          done

      - name: Run Unit Tests
        run: |
          python -m unittest discover tests

      - name: Build Docker Image
        run: docker build -t text2video-service .